require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CamelContextsController do

  # This should return the minimal set of attributes required to create a valid
  # CamelContext. As you add validations to CamelContext, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all camel_contexts as @camel_contexts" do
      camel_context = CamelContext.create! valid_attributes
      get :index
      assigns(:camel_contexts).should eq([camel_context])
    end
  end

  describe "GET show" do
    it "assigns the requested camel_context as @camel_context" do
      camel_context = CamelContext.create! valid_attributes
      get :show, :id => camel_context.id.to_s
      assigns(:camel_context).should eq(camel_context)
    end
  end

  describe "GET new" do
    it "assigns a new camel_context as @camel_context" do
      get :new
      assigns(:camel_context).should be_a_new(CamelContext)
    end
  end

  describe "GET edit" do
    it "assigns the requested camel_context as @camel_context" do
      camel_context = CamelContext.create! valid_attributes
      get :edit, :id => camel_context.id.to_s
      assigns(:camel_context).should eq(camel_context)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CamelContext" do
        expect {
          post :create, :camel_context => valid_attributes
        }.to change(CamelContext, :count).by(1)
      end

      it "assigns a newly created camel_context as @camel_context" do
        post :create, :camel_context => valid_attributes
        assigns(:camel_context).should be_a(CamelContext)
        assigns(:camel_context).should be_persisted
      end

      it "redirects to the created camel_context" do
        post :create, :camel_context => valid_attributes
        response.should redirect_to(CamelContext.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved camel_context as @camel_context" do
        # Trigger the behavior that occurs when invalid params are submitted
        CamelContext.any_instance.stub(:save).and_return(false)
        post :create, :camel_context => {}
        assigns(:camel_context).should be_a_new(CamelContext)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CamelContext.any_instance.stub(:save).and_return(false)
        post :create, :camel_context => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested camel_context" do
        camel_context = CamelContext.create! valid_attributes
        # Assuming there are no other camel_contexts in the database, this
        # specifies that the CamelContext created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CamelContext.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => camel_context.id, :camel_context => {'these' => 'params'}
      end

      it "assigns the requested camel_context as @camel_context" do
        camel_context = CamelContext.create! valid_attributes
        put :update, :id => camel_context.id, :camel_context => valid_attributes
        assigns(:camel_context).should eq(camel_context)
      end

      it "redirects to the camel_context" do
        camel_context = CamelContext.create! valid_attributes
        put :update, :id => camel_context.id, :camel_context => valid_attributes
        response.should redirect_to(camel_context)
      end
    end

    describe "with invalid params" do
      it "assigns the camel_context as @camel_context" do
        camel_context = CamelContext.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CamelContext.any_instance.stub(:save).and_return(false)
        put :update, :id => camel_context.id.to_s, :camel_context => {}
        assigns(:camel_context).should eq(camel_context)
      end

      it "re-renders the 'edit' template" do
        camel_context = CamelContext.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CamelContext.any_instance.stub(:save).and_return(false)
        put :update, :id => camel_context.id.to_s, :camel_context => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested camel_context" do
      camel_context = CamelContext.create! valid_attributes
      expect {
        delete :destroy, :id => camel_context.id.to_s
      }.to change(CamelContext, :count).by(-1)
    end

    it "redirects to the camel_contexts list" do
      camel_context = CamelContext.create! valid_attributes
      delete :destroy, :id => camel_context.id.to_s
      response.should redirect_to(camel_contexts_url)
    end
  end

end
